name = "libui_ng_prebuilt_jll"
uuid = "b42aaa73-0a05-4e59-960d-07cbce8fb00f"
version = "0.1.0"
authors = ["Fumiya Funatsu <funatsu.fumiya@gmail.com>"]

[deps]
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"

[compat]
Artifacts = "1.11.0"
